### ISSUE TITLE
Validation check: display summary to user

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/record-cleaner-ui#10]
Once the validation checks have been run, enable an on-screen summary showing something along these lines (can't remember which categories we are able to check at this point in the process):
- X records were checked for validation
- Y records failed due to issues with the location coordinates/grid references
- Z records failed due to incorrectly formatted dates
- ZZ records failed due to to names or taxon keys not being matched
- Please download the validation errors file, edit your data and re-upload to complete the checking process

Alternatively, if breaking things down by category is too complex, we could just display the overall total:
- X records were checked for validation
- Y records failed validation checks
- Please download the validation errors file to see the details, and then edit your data and re-upload to complete the checking process

**Comment by JimBacon** [comment]
First draft in dev. It also applies to verification results.

**Comment by JimBacon** [comment]
Deployed in v1.1.0
